spring:
  redis:
    host: 172.26.239.139
    port: 6379
    database: 0
  cache:
    redis:
      time-to-live: 1800000
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://172.26.239.139:3306/takeout_platform
    username: root
    password: root

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
