spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 172.26.239.115
    port: 6379
    database: 0
  cache:
    redis:
      time-to-live: 1800000
  shardingsphere:
    datasource:
      names: master, slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://172.26.239.115:3306/takeout_platform
        username: root
        password: root
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://172.26.239.5:3306/takeout_platform
        username: root
        password: root
    rules:
      readwrite-splitting:
        data-sources:
          master:
            static-strategy:
              write-data-source-name: master
              read-data-source-names: slave
            load-balancer-name: round_robin
        load-balancers:
          round_robin:
            type: ROUND_ROBIN
    props:
      sql:
        show: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl